import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  entries: [
    {
      input: './src/global/',
      outDir: `./dist/global`,
      addRelativeDeclarationExtensions: false,
      ext: 'js',
    },
    './src/modules/drupal/index.ts',
    {
      builder: 'copy',
      input: './src/modules/drupal/graphql',
      outDir: './dist/modules/drupal/graphql',
    },
    {
      input: './src/modules/drupal/runtime/',
      outDir: `./dist/modules/drupal/runtime`,
      addRelativeDeclarationExtensions: true,
      ext: 'js',
    },
  ],
  externals: [
    '#imports',
    '#blokkli/editor/adapter',
    '#blokkli/types',
    '#blokkli/icons',
    '#blokkli/constants',
    '#blokkli/definitions',
    '#blokkli/helpers',
    '#blokkli/helpers/broadcastProvider',
    '#blokkli/helpers/featuresProvider',
    '#blokkli/helpers/themeProvider',
    '#blokkli/helpers/tourProvider',
    '#blokkli/helpers/commandsProvider',
    '#blokkli/helpers/dropAreaProvider',
    '#blokkli/helpers/debugProvider',
    '#blokkli/translations',
    '#blokkli/generated-types',
    '#blokkli-build/module-types',
    '#blokkli-build/features',
    'defu',
    'unplugin',
    'magic-string',
    'ufo',
    'ohash',
    'typescript',
    'estree-walker',
    'oxc-walker',
    'micromatch',
    'acorn',
    'pathe',
    'graphql',
    'consola',
    'webpack-sources',
    'webpack-virtual-modules',
    '@jridgewell/sourcemap-codec',
    'nuxt-graphql-middleware/utils',
    '#nuxt-graphql-middleware/sources',
    '#graphql-operations',
  ],
  replace: {
    'import.meta.dev': 'undefined',
    'process.env.PLAYGROUND_MODULE_BUILD': 'undefined',
  },
})
