import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  externals: [
    '#imports',
    '#blokkli/adapter',
    '#blokkli/types',
    '#blokkli/icons',
    '#blokkli/constants',
    '#blokkli/definitions',
    '#blokkli/helpers',
    '#blokkli/helpers/broadcastProvider',
    '#blokkli/helpers/featuresProvider',
    '#blokkli/helpers/themeProvider',
    '#blokkli/helpers/tourProvider',
    '#blokkli/helpers/commandsProvider',
    '#blokkli/helpers/dropAreaProvider',
    '#blokkli/helpers/debugProvider',
    '#blokkli/translations',
    '#blokkli/generated-types',
    '#blokkli-build/module-types',
    'defu',
    'unplugin',
    'magic-string',
    'ufo',
    'ohash',
    'typescript',
    'estree-walker',
    'micromatch',
    'acorn',
    'pathe',
    'webpack-sources',
    'webpack-virtual-modules',
    '@jridgewell/sourcemap-codec',
  ],
  replace: {
    'import.meta.dev': 'undefined',
  },
})
