<template>
  <div v-if="totals.inputTokens > 0" class="bk-agent-token-usage">
    <ul>
      <li
        :title="
          $t('aiAgentTokensInput', 'Tokens used to send context to the AI')
        "
      >
        <div>{{ $t('aiAgentTokensInputLabel', 'Input') }}</div>
        <div>
          {{ ui.formatNumber(totals.inputTokens) }}
        </div>
      </li>
      <li class="bk-is-separator" />
      <li :title="$t('aiAgentTokensCached', 'Reused input tokens (cheaper)')">
        <div>{{ $t('aiAgentTokensCachedLabel', 'Cached') }}</div>
        <div>
          {{ ui.formatNumber(totals.cacheReadInputTokens) }}
        </div>
      </li>
      <li class="bk-is-separator" />
      <li
        :title="
          $t('aiAgentTokensOutput', 'Tokens generated by the AI in responses')
        "
      >
        <div>{{ $t('aiAgentTokensOutputLabel', 'Output') }}</div>
        <div>{{ ui.formatNumber(totals.outputTokens) }}</div>
      </li>
      <li class="bk-is-separator" />
      <li
        :title="$t('aiAgentTokensCost', 'Estimated cost for this conversation')"
      >
        <div>{{ $t('aiAgentTokensCostLabel', 'Cost') }}</div>
        <div v-if="totals.cost !== null">{{ ui.formatPrice(totals.cost) }}</div>
      </li>
    </ul>
  </div>
</template>

<script lang="ts" setup>
import { computed, useBlokkli } from '#imports'
import type { UsageTurn } from '#blokkli/agent/shared/types'

const props = defineProps<{
  usageTurns: UsageTurn[]
}>()

const { $t, ui } = useBlokkli()

const totals = computed(() => {
  let inputTokens = 0
  let outputTokens = 0
  let cacheReadInputTokens = 0
  let cost = 0
  let hasPricing = false

  for (const turn of props.usageTurns) {
    inputTokens += turn.inputTokens
    outputTokens += turn.outputTokens
    cacheReadInputTokens += turn.cacheReadInputTokens
    if (turn.pricing) {
      hasPricing = true
      cost +=
        (turn.inputTokens * turn.pricing.input +
          turn.cacheCreationInputTokens * turn.pricing.cacheWrite +
          turn.cacheReadInputTokens * turn.pricing.cacheRead +
          turn.outputTokens * turn.pricing.output) /
        1_000_000
    }
  }

  return {
    inputTokens,
    outputTokens,
    cacheReadInputTokens,
    cost: hasPricing ? cost : null,
  }
})
</script>
