<template>
  <div
    class="py-8 whitespace-nowrap leading-none border-b border-b-mono-300 border-dashed"
  >
    <ul class="flex justify-evenly flex-1">
      <TokenUsageItem
        :tooltip="
          $t('aiAgentTokensInput', 'Tokens used to send context to the AI')
        "
        :title="$t('aiAgentTokensInputLabel', 'Input')"
        :value="ui.formatNumber(totals.inputTokens)"
      />
      <Separator />
      <TokenUsageItem
        :tooltip="$t('aiAgentTokensCached', 'Reused input tokens (cheaper)')"
        :title="$t('aiAgentTokensCachedLabel', 'Cached')"
        :value="ui.formatNumber(totals.cacheReadInputTokens)"
      />
      <Separator />
      <TokenUsageItem
        :tooltip="
          $t('aiAgentTokensOutput', 'Tokens generated by the AI in responses')
        "
        :title="$t('aiAgentTokensOutputLabel', 'Output')"
        :value="ui.formatNumber(totals.outputTokens)"
      />
      <Separator />
      <TokenUsageItem
        :tooltip="
          $t('aiAgentTokensCost', 'Estimated cost for this conversation')
        "
        :title="$t('aiAgentTokensCostLabel', 'Cost')"
        :value="totals.cost"
      />
    </ul>
  </div>
</template>

<script lang="ts" setup>
import { computed, useBlokkli } from '#imports'
import type { UsageTurn } from '#blokkli/agent/shared/types'
import TokenUsageItem from './Item.vue'
import Separator from './Separator.vue'

const props = defineProps<{
  usageTurns: UsageTurn[]
}>()

const { $t, ui } = useBlokkli()

const totals = computed(() => {
  let inputTokens = 0
  let outputTokens = 0
  let cacheReadInputTokens = 0
  let cost = 0

  for (const turn of props.usageTurns) {
    inputTokens += turn.inputTokens
    outputTokens += turn.outputTokens
    cacheReadInputTokens += turn.cacheReadInputTokens
    if (turn.pricing) {
      cost +=
        (turn.inputTokens * turn.pricing.input +
          turn.cacheCreationInputTokens * turn.pricing.cacheWrite +
          turn.cacheReadInputTokens * turn.pricing.cacheRead +
          turn.outputTokens * turn.pricing.output) /
        1_000_000
    }
  }

  return {
    inputTokens,
    outputTokens,
    cacheReadInputTokens,
    cost: ui.formatPrice(cost),
  }
})
</script>
