fragment paragraphsBlokkliEditState on ParagraphsBlokkliEditState {
  mutations {
    ...paragraphsBlokkliMutationItem
  }

  currentIndex
  currentUserIsOwner
  ownerName
  user: uid {
    id
  }
  textFieldValues(langcode: $langcode) {
    uuid
    fieldName
    value
    fieldType
    entityType
    entityBundle
  }

  mutatedState {
    fields(langcode: $langcode) {
      ...paragraphsBlokkliMutatedField
    }
    mutatedOptions: behaviorSettings
    hostOptions
    violations {
      ...paragraphsBlokkliViolation
    }
  }

  publishOptions {
    ...paragraphsBlokkliPublishOptions
  }

  entity {
    status
    label
    bundleLabel
  }

  mutatedEntity {
    ...pbMutatedEntity
  }

  stateSettings {
    ignoredAnalyzeIdentifiers
  }

  translationState {
    isTranslatable
    sourceLanguage
    availableLanguages {
      id
      name
    }
    translations {
      id
      url
      editUrl
      exists
      status
    }
  }
}
