fragment paragraphsBlokkliCurrentUser on ParagraphsBlokkliUser {
  id
  name
  use_blokkli: hasPermission(permission: "view paragraphs blokkli edit state")
  take_ownership: hasPermission(
    permission: "take ownership of paragraphs blokkli edit state"
  )
  create_library_item: hasPermission(
    permission: "create paragraph library item"
  )

  edit_library_item: hasPermission(permission: "edit paragraph library item")

  manage_default_templates: hasPermission(
    permission: "manage default paragraph templates"
  )

  create_comments: hasPermission(permission: "post comments")
  view_comments: hasPermission(permission: "access comments")
  use_agent: hasPermission(permission: "use paragraphs blokkli agent")
}
query pbConfig($entityType: String!, $entityBundle: String!) {
  currentUser: paragraphsBlokkliGetUser {
    ...paragraphsBlokkliCurrentUser
  }
  clipboards: pbGetSupportedClipboards {
    ...paragraphsBlokkliSupportedClipboard
  }
  features: paragraphsBlokkliAvailableFeatures {
    ...paragraphsBlokkliAvailableFeatures
  }
  allTypes: entityQuery(entityType: PARAGRAPHS_TYPE, limit: 999) {
    items {
      ...blokkliParagraphsType
    }
  }

  fieldConfig: pbGetFieldConfig {
    name
    label
    entityType
    entityBundle
    cardinality
    canEdit
    allowedBundles
  }

  editableFieldConfig: pbGetEditableFieldConfig(
    entityType: $entityType
    entityBundle: $entityBundle
  ) {
    name
    label
    entityType
    entityBundle
    type
    required
    maxLength
  }

  droppableFieldConfig: pbGetDroppableFieldConfig(
    entityType: $entityType
    entityBundle: $entityBundle
  ) {
    type: fieldType
    name
    label
    entityType
    entityBundle
    cardinality
    canEdit
    allowed {
      type: entityType
      bundles
    }
    required
  }

  urlPrefixes: pbGetUrlPrefixes {
    langcode
    prefix
  }

  entityTypeConfig: paragraphsBlokkliEntityTypeConfig {
    id: entityTypeId
    label
    bundles {
      id: bundle
      label
    }
  }
}

fragment paragraphsBlokkliAvailableFeatures on ParagraphsBlokkliAvailableFeatures {
  conversion
  comment
  library
  mutations
}

fragment paragraphsBlokkliSupportedClipboard on ParagraphsBlokkliSupportedClipboard {
  __typename
  ... on ParagraphsBlokkliSupportedClipboardImage {
    possibleParagraphBundles
    maxFileSize
    fileExtensions
  }

  ... on ParagraphsBlokkliSupportedClipboardFile {
    possibleParagraphBundles
    maxFileSize
    fileExtensions
  }

  ... on ParagraphsBlokkliSupportedClipboardRichText {
    possibleParagraphBundles
  }

  ... on ParagraphsBlokkliSupportedClipboardRemoteVideo {
    possibleParagraphBundles
    videoProviders
  }
}
