fragment pbAgentConversationItem on ParagraphsBlokkliAgentConversation {
  uuid
  title
  createdAt: created
  updatedAt: changed
  host {
    entityType
    entityUuid
    label
    editUrl: url
  }
  author {
    id
    name
    imageUrl
  }
}

fragment pbAgentConversation on ParagraphsBlokkliAgentConversation {
  ...pbAgentConversationItem
  clientState: dataUser
  serverState: dataServer
  hash
  feedback {
    ...pbAgentFeedbackItem
  }
}

fragment pbAgentFeedbackItem on ParagraphsBlokkliAgentFeedback {
  id
  createdAt
  rating
  explanation
  itemId
  conversationUuid
  author {
    id
    name
    imageUrl
  }
}

mutation paragraphsBlokkliAgentToken {
  token: paragraphsBlokkliAgentToken
}

mutation pbAgentConversationUpsert(
  $uuid: String!
  $title: String!
  $dataUser: String!
  $dataServer: String!
  $hash: String!
  $hostEntityType: String!
  $hostEntityUuid: String!
) {
  result: paragraphsBlokkliAgentConversationUpsert(
    uuid: $uuid
    title: $title
    dataUser: $dataUser
    dataServer: $dataServer
    hash: $hash
    hostEntityType: $hostEntityType
    hostEntityUuid: $hostEntityUuid
  ) {
    success
    errors
  }
}

mutation pbAgentConversationDelete($uuid: String!) {
  result: paragraphsBlokkliAgentConversationDelete(uuid: $uuid) {
    success
    errors
  }
}

mutation pbAgentConversationFeedback(
  $uuid: String!
  $itemId: String!
  $rating: ParagraphsBlokkliAgentFeedbackRating!
  $explanation: String
) {
  result: paragraphsBlokkliAgentConversationFeedback(
    uuid: $uuid
    itemId: $itemId
    rating: $rating
    explanation: $explanation
  ) {
    success
    errors
  }
}

query pbAgentConversation($uuid: String!) {
  conversation: paragraphsBlokkliAgentConversation(uuid: $uuid) {
    ...pbAgentConversation
  }
}

query pbAgentConversationLatest($host: ParagraphsBlokkliHostEntityInput!) {
  conversation: paragraphsBlokkliAgentConversationLatest(host: $host) {
    ...pbAgentConversation
  }
}

query pbAgentConversations($host: ParagraphsBlokkliHostEntityInput!) {
  result: paragraphsBlokkliAgentConversations(host: $host) {
    items {
      uuid
      title
      createdAt: created
      updatedAt: changed
    }
  }
}

query pbAgentConversationsAll($page: Int) {
  result: paragraphsBlokkliAgentConversations(page: $page) {
    filters {
      ...paragraphsBlokkliConfigInput
    }
    items {
      ...pbAgentConversationItem
    }
    perPage
    total
  }
}

query pbAgentFeedbackAll($page: Int) {
  result: paragraphsBlokkliAgentConversationFeedbacks(page: $page) {
    filters {
      ...paragraphsBlokkliConfigInput
    }
    items {
      ...pbAgentFeedbackItem
    }
    perPage
    total
  }
}
