fragment paragraphsBlokkliComment on CommentBlokkliNode {
  uuid
  blockUuids: fieldTargetUuids
  resolved: fieldResolved
  body: commentBody
  created: createdRawField {
    first {
      value
    }
  }
  user: uid {
    label
  }
}

query pbComments(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
) {
  state: getParagraphsEditState(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
  ) {
    comments {
      ...paragraphsBlokkliComment
    }
  }
}

mutation pbAddComment(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
  $blockUuids: [String]!
  $body: String!
) {
  action: paragraphsBlokkliAddComment(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
    body: $body
    paragraphUuids: $blockUuids
  ) {
    ...paragraphsBlokkliComment
  }
}

mutation pbResolveComment(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
  $uuid: String!
) {
  action: paragraphsBlokkliResolveComment(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
    uuid: $uuid
  ) {
    ...paragraphsBlokkliComment
  }
}
