fragment paragraphsBlokkliComment on ParagraphsBlokkliComment {
  uuid
  blockUuids
  resolved
  body
  created
  updated
  user {
    id
    name
  }
}

query pbComments(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
) {
  state: getParagraphsEditState(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
  ) {
    comments {
      ...paragraphsBlokkliComment
    }
  }
}

mutation pbAddComment(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
  $blockUuids: [String]!
  $body: String!
  $parentUuid: String
) {
  action: paragraphsBlokkliAddComment(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
    body: $body
    paragraphUuids: $blockUuids
    parentUuid: $parentUuid
  ) {
    ...paragraphsBlokkliComment
  }
}

mutation pbEditComment(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
  $uuid: String!
  $body: String!
) {
  action: paragraphsBlokkliEditComment(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
    uuid: $uuid
    body: $body
  ) {
    ...paragraphsBlokkliComment
  }
}

mutation pbDeleteComment(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
  $uuid: String!
) {
  action: paragraphsBlokkliDeleteComment(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
    uuid: $uuid
  ) {
    ...paragraphsBlokkliComment
  }
}

mutation pbResolveComment(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
  $uuid: String!
) {
  action: paragraphsBlokkliResolveComment(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
    uuid: $uuid
  ) {
    ...paragraphsBlokkliComment
  }
}

mutation pbUnresolveComment(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
  $uuid: String!
) {
  action: paragraphsBlokkliUnresolveComment(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
    uuid: $uuid
  ) {
    ...paragraphsBlokkliComment
  }
}

mutation pbToggleCommentTaskItem(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
  $uuid: String!
  $taskIndex: Int!
) {
  action: paragraphsBlokkliToggleCommentTaskItem(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
    uuid: $uuid
    taskIndex: $taskIndex
  ) {
    ...paragraphsBlokkliComment
  }
}
