query pbConversions {
  paragraphsBlokkliConversions {
    ...paragraphsBlokkliConversion
  }
}

fragment paragraphsBlokkliConversion on ParagraphsBlokkliConversion {
  sourceBundle
  targetBundle
}

mutation pbConvertParagraph(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String
  $uuid: String!
  $targetBundle: String!
) {
  state: paragraphsEditMutationState(
    entityType: $entityType
    entityUuid: $entityUuid
  ) {
    action: convert(uuid: $uuid, targetBundle: $targetBundle) {
      ...paragraphsBlokkliMutationResult
    }
  }
}

mutation pbConvertMultiple(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String
  $uuids: [String]!
  $targetBundle: String!
) {
  state: paragraphsEditMutationState(
    entityType: $entityType
    entityUuid: $entityUuid
  ) {
    action: convert_multiple(uuids: $uuids, targetBundle: $targetBundle) {
      ...paragraphsBlokkliMutationResult
    }
  }
}
