query pbGetImportSourceEntities(
  $entityType: String!
  $entityUuid: String!
  $filters: [ParagraphsBlokkliUserConfigInput]
  $page: Int
) {
  pbGetImportSourceEntities(
    entityType: $entityType
    entityUuid: $entityUuid
    filters: $filters
    page: $page
  ) {
    total
    perPage
    filters {
      ...paragraphsBlokkliConfigInput
    }
    items {
      uuid
      label
      description
    }
  }
}

mutation pbCopyFromExisting(
  $entityType: EntityType!
  $entityUuid: String!
  $fields: [String]!
  $sourceUuid: String!
  $langcode: String
) {
  state: paragraphsEditMutationState(
    entityType: $entityType
    entityUuid: $entityUuid
  ) {
    action: copy_from_existing(fields: $fields, sourceUuid: $sourceUuid) {
      ...paragraphsBlokkliMutationResult
    }
  }
}
