query pbGetHostTransformPlugins(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
) {
  paragraphsBlokkliGetHostTransformPlugins(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
  ) {
    id
    label
    description
    allowPreview
    configInputs {
      ...paragraphsBlokkliConfigInput
    }
  }
}

mutation pbApplyHostTransformPlugin(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String
  $pluginId: String!
  $config: [ParagraphsBlokkliUserConfigInput]
  $preview: Boolean
) {
  state: paragraphsEditMutationState(
    entityType: $entityType
    entityUuid: $entityUuid
    preview: $preview
  ) {
    action: host_transform(pluginId: $pluginId, userConfig: $config) {
      ...paragraphsBlokkliMutationResult
    }
  }
}
