query pbGetTransformPlugins(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String!
) {
  paragraphsBlokkliGetTransformPlugins(
    entityType: $entityType
    entityUuid: $entityUuid
    langcode: $langcode
  ) {
    id
    label
    description
    bundles
    targetBundles
    min
    max
    allowPreview
    configInputs {
      ...paragraphsBlokkliConfigInput
    }
  }
}

mutation pbApplyTransformPlugin(
  $entityType: EntityType!
  $entityUuid: String!
  $langcode: String
  $pluginId: String!
  $uuids: [String]!
  $config: [ParagraphsBlokkliUserConfigInput]
  $preview: Boolean
) {
  state: paragraphsEditMutationState(
    entityType: $entityType
    entityUuid: $entityUuid
    preview: $preview
  ) {
    action: transform(pluginId: $pluginId, uuids: $uuids, userConfig: $config) {
      ...paragraphsBlokkliMutationResult
    }
  }
}
