query pbSearch($id: String!, $text: String!) {
  paragraphsBlokkliSearch(id: $id, text: $text) {
    text
    title
    context
    id: entityId
    imageUrl
    entityType
    entityBundle
    targetBundles
  }
}

query pbSearchTabs {
  tabs: paragraphsBlokkliSearchTabs {
    id
    label
  }
}

query pbSearchEditStates($page: Int) {
  pbSearchEditStates(page: $page) {
    perPage
    total
    items {
      uuid
      hostEntityUuid
      hostEntityType
      label
      currentUserIsOwner
      entity {
        label
        status
        bundleLabel
      }
    }
  }
}
