<template>
  <Teleport to="body">
    <transition name="bk-slide-in" :duration="200">
      <Overlay v-if="placedAction" @close="onClose" @submit="onSubmit" />
    </transition>
  </Teleport>

  <PluginAddAction
    type="assistant"
    :title="$t('assistantAddAction', 'Add with AI Assistant')"
    icon="robot"
    color="rose"
    @placed="placedAction = $event"
  />
</template>

<script lang="ts" setup>
import type { ActionPlacedEvent, AssistantResult } from '#blokkli/types'
import { useBlokkli, defineBlokkliFeature, ref } from '#imports'
import { PluginAddAction } from '#blokkli/plugins'
import Overlay from './Overlay/index.vue'

const { adapter } = defineBlokkliFeature({
  id: 'assistant',
  icon: 'robot',
  label: 'Assistant',
  description:
    'Provides a dynamic add block action to add one or more blocks generated by an AI assistant.',
  requiredAdapterMethods: [
    'assistantGetResults',
    'assistantAddBlockFromResult',
  ],
})

const { state, $t, eventBus } = useBlokkli()

const placedAction = ref<ActionPlacedEvent | null>(null)

const onClose = () => {
  placedAction.value = null
}

const onSubmit = async (result: AssistantResult) => {
  if (adapter.assistantAddBlockFromResult && placedAction.value) {
    // All the existing UUIDs on the page.
    const existingUuids = state.renderedBlocks.value.map((v) => v.item.uuid)

    await state.mutateWithLoadingState(
      adapter.assistantAddBlockFromResult({
        result,
        host: placedAction.value.host,
        preceedingUuid: placedAction.value.preceedingUuid,
      }),
      $t('assistantAddResultError', 'Failed to add block from assistant.'),
    )

    // Try to find the new block that has been added.
    const newUuid = state.renderedBlocks.value.find(
      (v) => !existingUuids.includes(v.item.uuid),
    )?.item.uuid
    if (newUuid) {
      eventBus.emit('select', newUuid)
    }
  }

  onClose()
}
</script>
<script lang="ts">
export default {
  name: 'Assistant',
}
</script>
