/** @type {import('tailwindcss').Config} */
module.exports = {
  corePlugins: {
    container: false,
  },
  theme: {
    fontFamily: {
      sans: ['PB Inter, sans-serif'],
    },
    colors: {
      accent: {
        50: 'rgb(var(--bk-theme-accent-50) / <alpha-value>)',
        100: 'rgb(var(--bk-theme-accent-100) / <alpha-value>)',
        200: 'rgb(var(--bk-theme-accent-200) / <alpha-value>)',
        300: 'rgb(var(--bk-theme-accent-300) / <alpha-value>)',
        400: 'rgb(var(--bk-theme-accent-400) / <alpha-value>)',
        500: 'rgb(var(--bk-theme-accent-500) / <alpha-value>)',
        600: 'rgb(var(--bk-theme-accent-600) / <alpha-value>)',
        700: 'rgb(var(--bk-theme-accent-700) / <alpha-value>)',
        800: 'rgb(var(--bk-theme-accent-800) / <alpha-value>)',
        900: 'rgb(var(--bk-theme-accent-900) / <alpha-value>)',
        950: 'rgb(var(--bk-theme-accent-950) / <alpha-value>)',
      },
      mono: {
        50: 'rgb(var(--bk-theme-mono-50) / <alpha-value>)',
        100: 'rgb(var(--bk-theme-mono-100) / <alpha-value>)',
        200: 'rgb(var(--bk-theme-mono-200) / <alpha-value>)',
        300: 'rgb(var(--bk-theme-mono-300) / <alpha-value>)',
        400: 'rgb(var(--bk-theme-mono-400) / <alpha-value>)',
        500: 'rgb(var(--bk-theme-mono-500) / <alpha-value>)',
        600: 'rgb(var(--bk-theme-mono-600) / <alpha-value>)',
        700: 'rgb(var(--bk-theme-mono-700) / <alpha-value>)',
        800: 'rgb(var(--bk-theme-mono-800) / <alpha-value>)',
        900: 'rgb(var(--bk-theme-mono-900) / <alpha-value>)',
        950: 'rgb(var(--bk-theme-mono-950) / <alpha-value>)',
      },
      teal: {
        light: 'rgb(var(--bk-theme-teal-light) / <alpha-value>)',
        normal: 'rgb(var(--bk-theme-teal-normal) / <alpha-value>)',
        dark: 'rgb(var(--bk-theme-teal-dark) / <alpha-value>)',
      },
      yellow: {
        light: 'rgb(var(--bk-theme-yellow-light) / <alpha-value>)',
        normal: 'rgb(var(--bk-theme-yellow-normal) / <alpha-value>)',
        dark: 'rgb(var(--bk-theme-yellow-dark) / <alpha-value>)',
      },
      red: {
        light: 'rgb(var(--bk-theme-red-light) / <alpha-value>)',
        normal: 'rgb(var(--bk-theme-red-normal) / <alpha-value>)',
        dark: 'rgb(var(--bk-theme-red-dark) / <alpha-value>)',
      },
      lime: {
        light: 'rgb(var(--bk-theme-lime-light) / <alpha-value>)',
        normal: 'rgb(var(--bk-theme-lime-normal) / <alpha-value>)',
        dark: 'rgb(var(--bk-theme-lime-dark) / <alpha-value>)',
      },
      white: 'white',
      black: 'black',
      transparent: 'transparent',
      current: 'currentColor',
    },
    spacing: {
      770: '770px',
      340: '340px',
      300: '300px',
      200: '200px',
      120: '120px',
      100: '100px',
      90: '90px',
      80: '80px',
      70: '70px',
      60: '60px',
      50: '50px',
      40: '40px',
      30: '30px',
      25: '25px',
      20: '20px',
      15: '15px',
      10: '10px',
      5: '5px',
      3: '3px',
      2: '2px',
      1: '1px',
      0: '0px',
    },
    borderWidth: {
      DEFAULT: '1px',
      0: '0',
      2: '2px',
      3: '3px',
      4: '4px',
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography')({
      className: 'ck-content',
    }),
  ],
}
