<template>
  <Teleport :to="ui.mainLayoutElement.value">
    <BlokkliTransition name="slide-in">
      <Overlay v-if="placedAction" @close="onClose" @submit="onSubmit" />
    </BlokkliTransition>
  </Teleport>
</template>

<script lang="ts" setup>
import { useBlokkli, defineBlokkliFeature, ref } from '#imports'
import { BlokkliTransition } from '#blokkli/editor/components'
import Overlay from './Overlay/index.vue'
import { defineAddAction } from '#blokkli/editor/composables'
import type { AssistantResult } from './types'
import type { ActionPlacedData } from '#blokkli/editor/types/actions'

const { adapter } = defineBlokkliFeature({
  id: 'assistant',
  icon: 'robot',
  label: 'Assistant',
  description:
    'Provides a dynamic add block action to add one or more blocks generated by an AI assistant.',
  requiredAdapterMethods: [
    'assistantGetResults',
    'assistantAddBlockFromResult',
  ],
  screenshot: 'feature-assistant.jpg',
  dependencies: ['add-list'],
})

const { state, $t, ui } = useBlokkli()

const placedAction = ref<ActionPlacedData | null>(null)

const onClose = () => {
  placedAction.value = null
}

const onSubmit = async (result: AssistantResult) => {
  if (adapter.assistantAddBlockFromResult && placedAction.value) {
    await state.mutateWithLoadingState(
      () =>
        adapter.assistantAddBlockFromResult({
          result,
          host: placedAction.value!.host,
          preceedingUuid: placedAction.value!.preceedingUuid,
        }),
      $t('assistantAddResultError', 'Failed to add block from assistant.'),
    )
  }

  onClose()
}

defineAddAction(() => {
  return {
    id: 'assistant',
    title: $t('assistantAddAction', 'Add with AI Assistant'),
    description: $t(
      'assistantAddActionDescription',
      'Add content using an AI assistant.',
    ),
    icon: 'robot',
    color: 'rose',
    weight: 0,
    callback: (data) => {
      placedAction.value = data
    },
  }
})
</script>

<script lang="ts">
export default {
  name: 'Assistant',
}
</script>
